# Generated by Django 5.1.3 on 2024-12-13 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('church_name', models.CharField(max_length=100)),
                ('abode', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Respect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('area_name', models.CharField(max_length=100)),
                ('area_id', models.CharField(max_length=20, unique=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.church')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'ordering': ['area_id'],
            },
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fellowship_name', models.CharField(max_length=100)),
                ('fellowship_id', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.area')),
            ],
            options={
                'verbose_name_plural': 'Fellowships',
                'ordering': ['fellowship_id'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('family_id', models.CharField(max_length=20)),
                ('initial', models.CharField(max_length=10)),
                ('family_head', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('prayer_points', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.area')),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.fellowship')),
                ('respect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.respect')),
            ],
            options={
                'verbose_name_plural': 'Families',
                'unique_together': {('family_id', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Pastorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pastorate_name', models.CharField(max_length=100)),
                ('pastorate_short_name', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='church',
            name='pastorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.pastorate'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('member_id', models.CharField(max_length=30, unique=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('initial', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dom', models.DateField(blank=True, null=True)),
                ('working', models.CharField(blank=True, max_length=100)),
                ('working_place', models.CharField(blank=True, max_length=100)),
                ('baptised', models.BooleanField(default=False)),
                ('date_of_bap', models.DateField(blank=True, null=True)),
                ('conformed', models.BooleanField(default=False)),
                ('date_of_conf', models.DateField(blank=True, null=True)),
                ('death', models.BooleanField(default=False)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_images/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.family')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='congregation.member')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.relation')),
                ('respect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.respect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
