# Generated by Django 5.1.3 on 2024-12-03 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=100)),
                ('adobe', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('area_id', models.CharField(max_length=20, unique=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.church')),
            ],
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fellowship_name', models.CharField(max_length=100)),
                ('fellowship_id', models.CharField(max_length=20, unique=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.church')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=20)),
                ('respect', models.CharField(max_length=10)),
                ('initial', models.CharField(max_length=10)),
                ('family_head', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('prayer_points', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.area')),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.fellowship')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('respect', models.CharField(max_length=10)),
                ('initial', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('dom', models.DateField(blank=True, null=True)),
                ('working', models.CharField(max_length=100)),
                ('working_place', models.CharField(max_length=100)),
                ('baptised', models.BooleanField(default=False)),
                ('date_of_bap', models.DateField(blank=True, null=True)),
                ('conformed', models.BooleanField(default=False)),
                ('date_of_conf', models.DateField(blank=True, null=True)),
                ('death', models.BooleanField(default=False)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='member_images/')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.family')),
            ],
        ),
        migrations.CreateModel(
            name='Pastorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastorate_name', models.CharField(max_length=100)),
                ('pastorate_short_name', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='church',
            name='pastorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.pastorate'),
        ),
    ]
