# Generated by Django 5.1.3 on 2024-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='position_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
