# Generated by Django 5.1.3 on 2024-12-03 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congregation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='pastorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congregation.pastorate'),
        ),
        migrations.AddField(
            model_name='member',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.relation'),
        ),
        migrations.AddField(
            model_name='member',
            name='respect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.respect'),
        ),
        migrations.AddField(
            model_name='family',
            name='respect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.respect'),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('family_id', 'area')},
        ),
    ]
