# Generated by Django 5.1.3 on 2024-12-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0004_rename_adobe_to_abode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Respect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.AddField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('family_id', 'area')},
        ),
        migrations.AlterField(
            model_name='member',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.relation'),
        ),
        migrations.AlterField(
            model_name='family',
            name='respect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.respect'),
        ),
        migrations.AlterField(
            model_name='member',
            name='respect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='congregation.respect'),
        ),
    ]
