# Generated by Django 5.1.3 on 2024-12-03 04:54

from django.db import migrations

def add_initial_respect_titles(apps, schema_editor):
    Respect = apps.get_model('congregation', 'Respect')
    respect_titles = ['Mr.', 'Mrs.', 'Miss.', 'Dr.', 'Rev.', 'Prof.']
    for title in respect_titles:
        Respect.objects.create(name=title)

def remove_respect_titles(apps, schema_editor):
    Respect = apps.get_model('congregation', 'Respect')
    Respect.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0005_relation_respect_alter_family_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_respect_titles, remove_respect_titles),
    ]
