# Generated by Django 5.1.3 on 2024-12-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0008_cleanup_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='initial',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='working',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='working_place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
