# Generated by Django 5.1.3 on 2024-12-03 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congregation', '0009_alter_member_aadhar_number_alter_member_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='congregation.member'),
        ),
    ]
