# Generated by Django 5.1.3 on 2024-12-03 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('congregation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='ledger_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.ledgergroup'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.transactioncategory'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offertory_transactions', to='congregation.church'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.transaction'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('church', 'name'), ('pastorate', 'name')},
        ),
    ]
