# Generated by Django 5.1.3 on 2024-12-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_diocesecontracategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diocesetransaction',
            name='linked_transaction',
        ),
    ]
