# Generated by Django 5.1.3 on 2024-12-05 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('congregation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Primary Categories',
            },
        ),
        migrations.RemoveField(
            model_name='transactioncategory',
            name='ledger_group',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='church',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='aqudence_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='aqudence_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='congregation.church'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, help_text='For contra entries only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='aqudence_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='aqudence_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='member_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('bill', 'Bill/Voucher'), ('aqudence', 'Aqudence'), ('offering', 'Church Offering'), ('custom_debit', 'Custom Debit'), ('custom_credit', 'Custom Credit'), ('contra', 'Contra Entry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.primarycategory'),
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary_categories', to='accounts.primarycategory')),
            ],
            options={
                'verbose_name_plural': 'Secondary Categories',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='secondary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.secondarycategory'),
        ),
        migrations.DeleteModel(
            name='LedgerGroup',
        ),
        migrations.DeleteModel(
            name='TransactionCategory',
        ),
        migrations.DeleteModel(
            name='TransactionDetail',
        ),
    ]
