# Generated by Django 5.1.3 on 2024-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_primarycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondarycategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
