# Generated by Django 5.1.3 on 2024-12-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_primarycategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='primary_category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='secondary_category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, help_text='For contra credit entries only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, help_text='For contra debit entries only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('bill', 'Bill/Voucher'), ('aqudence', 'Aqudence'), ('offering', 'Church Offering'), ('custom_debit', 'Custom Debit'), ('custom_credit', 'Custom Credit'), ('contra', 'Contra Entry (Debit)'), ('contra_credit', 'Contra Entry (Credit)')], max_length=20),
        ),
    ]
