# Generated by Django 5.1.3 on 2024-12-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_transaction_primary_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.primarycategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='secondary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.secondarycategory'),
        ),
    ]
